services:
  - type: web
    name: opti-crm
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: VITE_API_URL
        value: "https://opti-crm-backend.onrender.com"
      - key: VITE_WS_URL
        value: "wss://opti-crm-backend.onrender.com/ws"
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    pullRequestPreviewsEnabled: true
