services:
  - type: static
    name: opti-crm
    buildCommand: npm install && npm run build
    publishDir: dist
    staticPublishPath: /
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
