services:
  - type: static
    name: opti-crm
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    publishDir: dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
