services:
  - type: static
    name: opti-crm
    buildCommand: npm install && npm run build
    staticPublishPath: /
    publishDir: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
